[tool.poetry]
name = "temed_llm"
version = "0.1.0"
description = "TEMED-LLM: Medical Text to Tabular Data Conversion System"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
# Add your other dependencies here

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"